services:
  mysql:
    image: mysql:9.2.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bibliotech
    container_name: bibliotech-db
    networks:
      - bibliotech-bridge
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 7

  bibliotech:
    image: bibliotech
    build: .
    container_name: bibliotech
    networks:
      - bibliotech-bridge
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

networks:
  bibliotech-bridge:
    driver: bridge