spring.application.name=bibliotech
server.port=8080
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bibliotech
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/bibliotech
